apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calendar-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calendar-service
  template:
    metadata:
      labels:
        app: calendar-service
    spec:
      containers:
        - name: calendar-service
          image: 115.68.198.240:30002/cowork-msa/calendar-service:latest
          ports:
            - containerPort: 8772
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8888
            - name: spring.rabbitmq.host
              value: rabbitmq
            - name: eureka.client.service-url.defaultZone
              value: http://discovery-service:8761/eureka
          resources:
            limits:
              cpu: "70m"
              memory: 500Mi
            requests:
              cpu: "70m"
              memory: 500Mi
      imagePullSecrets:
        - name: cowork-msa-secret
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-service
spec:
  selector:
    app: calendar-service
  ports:
    - protocol: TCP
      port: 8772
      targetPort: 8772
      nodePort: 30050
  type: NodePort
